sa-token:
  token-name: pb-token
  timeout: 604800
  activity-timeout: 259200
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  jwt-secret-key: kjvwy2jkfsdhk

spring:
  profiles:
    active: dev
  data:
    redis:
      database: 0
      timeout: 3000
      password: null
      host: 127.0.0.1
      port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

wechat:
  appid: wxc9615a04550bbfdb
  secret: ef309aba284fc74a6a5228f12d3803e7

x-ti:
  appid: 4d396e1c42d3e921609d2c6a3c01cd7b
  secret: a04c2bd6f1946277d5135d976d0e4954