package team.delete.pursebuddy.constant;

import lombok.Getter;

/**
 * @author patrick_star
 * @Desc  各种状态枚举类
 * @version 1.0
 */
@Getter
public enum StatusConstant {
    //项目状态(1:待提交、2:已提交、3:已退回、4:已完结) 学生视角
    PROJECT_STUDENT_STATUS_WAIT_FOR_SUBMIT(1),
    PROJECT_STUDENT_STATUS_SUBMITTED(2),
    PROJECT_STUDENT_STATUS_RETURN(3),
    PROJECT_STUDENT_STATUS_COMPELETED(4),
    //项目是否进入下一个阶段
    PROJECT_NOT_ENTER_NEXT_STAGE(0),
    PROJECT_PERMITTED_ENTER_NEXT_STAGE(1),
    PROJECT_ENTERED_NEXT_STAGE(2),
    //项目是否删除
    PROJECT_DELETED(1),
    PROJECT_NOT_DELETE(0),
    //小阶段顺序(1：提交、2：审核、3：公示)
    COMPETITION_STAGE_STATUS_ORDER_SUBMIT(1),
    COMPETITION_STAGE_STATUS_ORDER_JUDGE(2),
    COMPETITION_STAGE_STATUS_ORDER_PROMULGATE(3),
    //赛事进行状态(1:未开始、2:进行中、3:已完结)
    COMPETITION_STATUS_NOT_COMMENCED(1),
    COMPETITION_STATUS_ONGOING(2),
    COMPETITION_STATUS_COMPELETED(3),
    //赛事阶段（1:初赛、2：复赛）
    COMPETITION_STAGE_PRELIMINARY(1),
    COMPETITION_STAGE_FINAL(2),
    //需要院级管理员审核
    COMPETITION_NEED_ACADEMY_REC(1),
    COMPETITION_NOT_NEED_ACADEMY_REC(0),
    //院级管理员视角-项目状态   1:不可见（学生未提交）、2:未审核、3:退回修改、4:已审核)
    PROJECT_STATUS_ACADEMY_VERSION_INVISIBLE(1),
    PROJECT_STATUS_ACADEMY_VERSION_WAIT_FOR_JUDGE(2),
    PROJECT_STATUS_ACADEMY_VERSION_RETURN_FOR_MODIFY(3),
    PROJECT_STATUS_ACADEMY_VERSION_ALREADY_JUDGED(4),
    //校级管理员视角-项目状态   1：不可见（校级未推荐）、2:未审核、3:退回修改、4:已审核
    PROJECT_STATUS_SCHOOL_VERSION_INVISIBLE(1),
    PROJECT_STATUS_SCHOOL_VERSION_WAIT_FOR_JUDGE(2),
    PROJECT_STATUS_SCHOOL_VERSION_RETURN_FOR_MODIFY(3),
    PROJECT_STATUS_SCHOOL_VERSION_ALREADY_JUDGED(4),
    //是否拟推荐项目  0:否 1:是
    PROJECT_ALREADY_SUPPOSE_SUBMIT(1),
    PROJECT_NOT_SUPPOSE_SUBMIT(0),
    //是否已经提交推荐给校级管理员  0:否 1:是
    PROJECT_ALREADY_SUBMIT(1),
    PROJECT_NOT_SUBMIT(0),
    //是否省级推荐项目 0:否 1:是
    PROJECT_IS_PROVINCE_REC(1),
    PROJECT_IS_NOT_PROVINCE_REC(0),
    //是否校团委直推项目 0:否 1:是
    PROJECT_IS_SCHOOL_COMMUNITY_REC(1),
    PROJECT_IS_NOT_SCHOOL_COMMUNITY_REC(0),
    //项目奖励
    PROJECT_AWARD_SUPER_PRIZE(0),
    PROJECT_AWARD_FIRST_PRIZE(1),
    PROJECT_AWARD_SECOND_PRIZE(2),
    PROJECT_AWARD_THIRD_PRIZE(3),
    PROJECT_AWARD_ACADEMY_THIRD_PRIZE(4),
    PROJECT_AWARD_ENCOURAGE_PRIZE(5),
    //身份信息
    IDENTITY_STUDENT(1),
    IDENTITY_JUDGE(2),
    IDENTITY_ACADEMY_ADMIN(3),
    IDENTITY_SCHOOL_ADMIN(4),
    IDENTITY_SUPER_ADMIN(5),
    //比赛阶段状态
    COMPETITION_STAGE_STATUS_NOT_COMMENCED(1),
    COMPETITION_STAGE_STATUS_ONGOING(2),
    COMPETITION_STAGE_STATUS_COMPLETED(3),
    //申请评委评审信息申请状态
    COMPETITION_APP_JUDGE_STATUS_WAIT_TO_CHECK(1),
    COMPETITION_APP_JUDGE_STATUS_NOT_ALLOW(2),
    COMPETITION_APP_JUDGE_STATUS_ALLOW(3),
    //消息种类
    MSG_TYPE_IN_TEAM(1),
    MSG_TYPE_PROJECT_RETURN(2),
    MSG_TYPE_APP_JUDGE(3),
    MSG_TYPE_PROJECT_ENTER_NEXT_STAGE(4),
    MSG_TYPE_USER_MSG(5),
    //发消息的Aha君ID
    MSG_SYS_SENDER(1),
    //队伍排名
    RANK_LEADER(1)
    ;



    private final Integer code;

    StatusConstant(Integer code) {
        this.code = code;
    }
}
